version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clyr
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/clyr
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

networks:
  app-network:
    name: my-custom-network
    driver: bridge

volumes:
  mysql_data:
